(function(){window.Fkd={createNamespace:function(a){a=a.split(".");for(var b=window,c=0,d=a.length;c<d;c++){if("object"!=typeof b[a[c]])b[a[c]]={};b=b[a[c]]}return b[a[c]]},extend:function(a){var b,c=b=function(){a.apply(this,arguments)};b.prototype=new a;b.prototype.constructor=c;b.superClass=a.prototype;b.prototype.superClass=function(){return a.prototype};return b},createDelegate:function(a,b){return function(){a.apply(b,arguments)}},call_fn_array:function(a,b){if("function"==typeof a)a.apply(a,
b);else a.scope&&a.fn&&a.apply(scope,b)}};Fkd.createNamespace("freakdev.utils");freakdev.utils.Dom={get:function(a){return document.getElementById(a)},getByTagName:function(a){return document.getElementsByTagName(a)}};var g=freakdev.utils.Dom;Fkd.createNamespace("freakdev.utils");freakdev.utils.Debug=function(){var a=true,b;return{setDebugMode:function(c){a=c},setDebugPanel:function(c){if(c=freakdev.utils.Dom.get(c))b=c},print:function(c){if(a)if(b){b.appendChild(document.createTextNode(c));b.appendChild(document.createElement("br"))}else window.console&&
console.log(c)}}}();Fkd.createNamespace("freakdev.utils");freakdev.utils.Uuid=function(){var a="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("");return function(b,c){var d=[],e=Math.random;c=c||a.length;if(b)for(var f=0;f<b;f++)d[f]=a[0|e()*c];else{var h;d[8]=d[13]=d[18]=d[23]="-";d[14]="4";for(f=0;f<36;f++)if(!d[f]){h=0|e()*16;d[f]=a[f==19?h&3|8:h&15]}}return d.join("")}}();var i=freakdev.utils.Uuid;Fkd.createNamespace("freakdev.math");freakdev.math.Point=function(){this.init.apply(this,
arguments)};freakdev.math.Point.prototype.init=function(a,b){this.x=a;this.y=b};Fkd.createNamespace("freakdev.event");freakdev.event.CLICK="click";freakdev.event.DBLCLICK="dblclick";freakdev.event.MOUSE_DOWN="mousedown";freakdev.event.MOUSE_MOVE="mousemove";freakdev.event.MOUSE_OUT="mouseout";freakdev.event.MOUSE_OVER="mouseover";freakdev.event.MOUSE_UP="mouseup";freakdev.event.MOUSE_WHEEL="mousewheel";freakdev.event.KEY_DOWN="keydown";freakdev.event.KEY_PRESS="keypress";freakdev.event.KEY_UP="keyup";
freakdev.event.DRAG="drag";freakdev.event.DRAG_END="dragend";freakdev.event.DRAG_ENTER="dragenter";freakdev.event.DRAG_LEAVE="dragleave";freakdev.event.DRAG_OVER="dragover";freakdev.event.DRAG_START="dragstart";freakdev.event.DROP="drop";freakdev.event.DOM_EVENTS=["mousedown","mousemove","mouseout","mouseover","mouseup","mousewheel","keydown","keypress","keyup","drag","dragend","dragenter","dragleave","dragover","dragstart","drop"];freakdev.event.EventManager=function(){this.init.apply(this,arguments)};
freakdev.event.EventManager.prototype.init=function(){this._eventListeners=[];this._registeredEvents=[]};freakdev.event.EventManager.instance=null;freakdev.event.EventManager.getInstance=function(){if(null==freakdev.event.EventManager.instance)freakdev.event.EventManager.instance=new freakdev.event.EventManager;return freakdev.event.EventManager.instance};freakdev.event.EventManager.prototype.addEventListener=function(a,b,c){a=a instanceof freakdev.event.Event?a.getName():a;if(null==this._registeredEvents[a])this._registeredEvents[a]=
[];if(null==this._registeredEvents[a][c.getConstId()])this._registeredEvents[a][c.getConstId()]=[];this._registeredEvents[a][c.getConstId()].push(b)};freakdev.event.EventManager.prototype.removeEventListener=function(a,b,c){a=a instanceof freakdev.event.Event?a.getName():a;if(null!=this._registeredEvents[a])if(null!=this._registeredEvents[a][b.getConstId()]){c=this._registeredEvents[a][b.getConstId()];if(undefined!=c)delete this._registeredEvents[a][b.getConstId()][this._registeredEvents[a][b.getConstId()].indexOf(c)];
else delete this._registeredEvents[a][b.getConstId()][this._registeredEvents[a][b.getConstId()]]}};freakdev.event.EventManager.prototype.domEventFactory=function(a,b){if("mouse"==a.type.substr(0,5))return new freakdev.event.MouseEvent(a,b);else if("key"!=a.type.subtr(0,3))"drop"==a.type.subtr(0,4)||a.type.subtr(0,4)};freakdev.event.EventManager.prototype.fireEvent=function(a,b){var c=a instanceof freakdev.event.Event?a.getName():a;if(this._registeredEvents[c]&&this._registeredEvents[c][b.getConstId()]){c=
this._registeredEvents[c][b.getConstId()];for(var d=0,e=c.length;d<e;d++)(0,c[d])(a)}};Fkd.createNamespace("freakdev.event");freakdev.event.Event=function(){this.init.apply(this,arguments)};freakdev.event.Event.prototype.init=function(a){this._name=a;this._allowPropagation=true};freakdev.event.Event.prototype.getName=function(){return this._name};freakdev.event.Event.prototype.stopPropagation=function(){return this._allowPropagation=false};freakdev.event.Event.prototype.canPropagate=function(){return this._allowPropagation};
Fkd.createNamespace("freakdev.event");freakdev.event.MouseEvent=Fkd.extend(freakdev.event.Event);freakdev.event.MouseEvent.LEFT_BUTTON="lb";freakdev.event.MouseEvent.RIGHT_BUTTON="rb";freakdev.event.MouseEvent.prototype.init=function(a,b){freakdev.event.MouseEvent.superClass.init.call(this,a.type);this.canvas=b||a.target;this.type=a.type;this.button=1==a.button?freakdev.event.MouseEvent.LEFT_BUTTON:freakdev.event.MouseEvent.RIGHT_BUTTON;this.x=a.layerX-a.target.offsetLeft;this.y=a.layerY-a.target.offsetTop};
Fkd.createNamespace("freakdev.event");freakdev.event.EventHandler=function(){this.init.apply(this,arguments)};freakdev.event.EventHandler.prototype.init=function(){this._eventManager=freakdev.event.EventManager.getInstance();this._constUID=i()};freakdev.event.EventHandler.prototype.getConstId=function(){return this._constUID};freakdev.event.EventHandler.prototype.attachEvent=function(a,b){this._eventManager.addEventListener(a,b,this)};freakdev.event.EventHandler.prototype.detachEvent=function(a,b){this._eventManager.addEventListener(a,
this,b)};freakdev.event.EventHandler.prototype.fireEvent=function(a){this._eventManager.fireEvent(a,this)};freakdev.event.EventHandler.prototype.fireEventAsync=function(a){freakdev.thread.Broker.getInstance().startThread(this._eventManager.fireEvent,[a,this])};Fkd.createNamespace("freakdev.canvas.image");freakdev.canvas.image.Pixel=function(a,b,c,d,e){this.alpha=this.luminosity=this.saturation=this.hue=this.blue=this.green=this.red=0;if(undefined==e||"rgb"==e){this.red=a;this.green=b;this.blue=c}else if("hsl"==
e){this.hue=a;this.saturation=b;this.luminosity=c}this.alpha=d};freakdev.canvas.image.Pixel.prototype.toRGB=function(){var a=function(b,c,d){if(d<0)d+=1;if(d>1)d-=1;if(6*d<1)return b+(c-b)*6*d;if(2*d<1)return c;if(3*d<2)return b+(c-b)*(2/3-d)*6;return b};if(this.saturation==0){R=this.luminosity*255;G=this.luminosity*255;B=this.luminosity*255}else{var_2=this.luminosity<0.5?this.luminosity*(1+this.saturation):this.luminosity+this.saturation-this.saturation*this.luminosity;var_1=2*this.luminosity-var_2;
R=255*a(var_1,var_2,this.hue+1/3);G=255*a(var_1,var_2,this.hue);B=255*a(var_1,var_2,this.hue-1/3)}this.red=R;this.green=G;this.blue=B;return{red:R,green:G,blue:B}};freakdev.canvas.image.Pixel.prototype.toHSL=function(){var_R=this.red/255;var_G=this.green/255;var_B=this.blue/255;var_Min=Math.min(var_R,var_G,var_B);var_Max=Math.max(var_R,var_G,var_B);del_Max=var_Max-var_Min;L=(var_Max+var_Min)/2;if(del_Max==0)S=H=0;else{S=L<0.5?del_Max/(var_Max+var_Min):del_Max/(2-var_Max-var_Min);del_R=((var_Max-var_R)/
6+del_Max/2)/del_Max;del_G=((var_Max-var_G)/6+del_Max/2)/del_Max;del_B=((var_Max-var_B)/6+del_Max/2)/del_Max;if(var_R==var_Max)H=del_B-del_G;else if(var_G==var_Max)H=1/3+del_R-del_B;else if(var_B==var_Max)H=2/3+del_G-del_R;if(H<0)H+=1;if(H>1)H-=1}this.hue=H;this.saturation=S;this.luminosity=L;return{hue:H,sat:S,lig:L}};freakdev.canvas.image.Pixel.prototype.blend=function(a){undefined==this.red&&this.toRGB();this.red=(1-a.alpha)*this.red+a.alpha*a.red;this.green=(1-a.alpha)*this.green+a.alpha*a.green;
this.blue=(1-a.alpha)*this.blue+a.alpha*a.blue;this.alpha+=a.alpha;return this};Fkd.createNamespace("freakdev.canvas");freakdev.canvas.Canvas=function(){this.init.apply(this,arguments)};freakdev.canvas.Canvas.prototype.init=function(a){this.insertedToDom=false;this._autoRenderTimer=this.canvasNode=this._domPlaceholder=null;this._isRendering=false;this._fps=100;this.scene=null;this.getCanvas(undefined!=a?a:false);this._initScene();this._initEvent()};freakdev.canvas.Canvas.prototype._initScene=function(){this.scene=
new freakdev.canvas.scene.Scene(this);this.scene.setId("scene")};freakdev.canvas.Canvas.prototype._initEvent=function(){var a=Fkd.createDelegate(function(c){c=freakdev.event.EventManager.getInstance().domEventFactory(c,this);Fkd.createDelegate(this.scene.handleDomEvent,this.scene)(c)},this),b;for(b in freakdev.event.DOM_EVENTS)this.getCanvas().addEventListener(freakdev.event.DOM_EVENTS[b],a,true)};freakdev.canvas.Canvas.prototype.propagateEvent=function(a){this.scene.handleEvent.call(this,a)};freakdev.canvas.Canvas.prototype.getCanvas=
function(a){if(!this.canvasNode)if(a){this.canvasNode=g.get(a);this.insertedToDom=true}else this.canvasNode=document.createElement("canvas");return this.canvasNode};freakdev.canvas.Canvas.prototype.getContext=function(){return this.getCanvas().getContext("2d")};freakdev.canvas.Canvas.prototype.resize=function(a,b){this.getCanvas().width=a;this.getCanvas().height=b;this.scene.resize(a,b)};freakdev.canvas.Canvas.prototype.query=function(){};freakdev.canvas.Canvas.prototype.setDomPlaceholder=function(a){if("string"==
typeof a)a=g.get(a);if(null==a)a=g.getByTagName("body").item(0);this._domPlaceholder=a};freakdev.canvas.Canvas.prototype.getDomPlaceholder=function(){return this._domPlaceholder};freakdev.canvas.Canvas.prototype.render=function(){this._isRendering=true;this.scene.isRendering()||this.scene.isRenderNeeded()&&this.scene.renderTo(this);if(!this.insertedToDom){this.insertedToDom=true;var a;(a=arguments.length?this.setDomPlaceholder(arguments[0]):this.getDomPlaceholder())||(a=g.getByTagName("body").item(0));
a.appendChild(this.getCanvas())}this._isRendering=false};freakdev.canvas.Canvas.prototype.save=function(){this.getContext().save()};freakdev.canvas.Canvas.prototype.restore=function(a){if(undefined==a)a=1;for(var b=0;b<a;b++)this.getContext().restore()};freakdev.canvas.Canvas.prototype.updateContext=function(a,b,c){false!==c&&this.save();this.getContext()[a]=b};freakdev.canvas.Canvas.prototype.translateTo=function(a,b,c){false!==c&&this.save();this.getContext().translate(a,b)};freakdev.canvas.Canvas.prototype.translateToObjectCenter=
function(a,b){var c=a.getX()+parseInt(a.getWidth()/2),d=a.getY()+parseInt(a.getHeight()/2);this.translateTo(c,d,b)};freakdev.canvas.Canvas.prototype.rotate=function(a,b){false!==b&&this.save();this.getContext().rotate(a*Math.PI/180)};freakdev.canvas.Canvas.prototype.scale=function(a,b){this.scaleXY(a,a,b)};freakdev.canvas.Canvas.prototype.scaleXY=function(a,b,c){false!==c&&this.save();this.getContext().scale(a,b)};freakdev.canvas.Canvas.prototype.startAutoRender=function(a){undefined!=a&&this.setFps(a);
a=parseInt(1E3/this.getFps());this._autoRenderTimer=setInterval(Fkd.createDelegate(this.render,this),a)};freakdev.canvas.Canvas.prototype.setFps=function(a){this._fps=a};freakdev.canvas.Canvas.prototype.getFps=function(){return this._fps};freakdev.canvas.Canvas.prototype.stopAutoRender=function(){clearInterval(this._autoRenderTimer)};Fkd.createNamespace("freakdev.canvas.scene");freakdev.canvas.scene.Object=Fkd.extend(freakdev.event.EventHandler);freakdev.canvas.scene.Object.prototype.init=function(a,
b,c,d){this.id=freakdev.utils.Uuid();this._constId=freakdev.utils.Uuid();this._imgTag=new Image(c?c:null,d?d:null);this._naturalHeight=this._naturalWidth=0;this.x=undefined==a?0:a;this.y=undefined==b?0:b;this.focusStatus=this.activeStatus=false;this.visibilityStatus=true;this.opacity=1;this.rotation=0;this.scaleY=this.scaleX=1;this._container=null;this._needToRender=true;this._isRendering=false;this._eventListeners=[];this._anchorPoint={};this.resetAnchorPoint()};freakdev.canvas.scene.Object.prototype.setNeedToRender=
function(a){if(undefined==a)a=true;a&&null!=this._container&&this._container.setNeedToRender();this._needToRender=a};freakdev.canvas.scene.Object.prototype.resetAnchorPoint=function(){this._anchorPoint={x:0,y:0}};freakdev.canvas.scene.Object.prototype.setAnchorPoint=function(a,b){this._anchorPoint={x:a,y:b}};freakdev.canvas.scene.Object.prototype.setId=function(a){this.id=a};freakdev.canvas.scene.Object.prototype.getId=function(){return this.id};freakdev.canvas.scene.Object.prototype._prepareTarget=
function(a){if(this.opacity<1||0!=this.rotation||1!=this.getScaleX()||1!=this.getScaleY()){a.updateContext("globalAlpha",this.opacity);a.translateToObjectCenter(this);tmpX=this.getX();tmpY=this.getY();this.setX(-parseInt(this.getWidth()/2));this.setY(-parseInt(this.getHeight()/2));a.rotate(this.rotation);a.scale(this.getScaleX(),this.getScaleY())}};freakdev.canvas.scene.Object.prototype._restoreTarget=function(a){if(this.opacity<1||0!=this.rotation||1!=this.getScaleX()||1!=this.getScaleY()){a.restore(4);
this.setX(tmpX);this.setY(tmpY)}};freakdev.canvas.scene.Object.prototype.renderTo=function(a){if(this.isVisible()){this.isRenderNeeded()&&this.render();this.fireEvent("beforeRenderTo",this);this._prepareTarget(a);this._drawToTarget(a);this._restoreTarget(a);this.fireEvent("afterRenderTo",this)}};freakdev.canvas.scene.Object.prototype._drawToTarget=function(a){this._naturalWidth>0&&this._naturalHeight>0&&a.getContext().drawImage(this.getImgTag(),0,0,this._naturalWidth,this._naturalHeight,this.getX(),
this.getY(),this.getWidth(),this.getHeight())};freakdev.canvas.scene.Object.prototype.isRenderNeeded=function(){return this._needToRender};freakdev.canvas.scene.Object.prototype.setContainer=function(a){this._container=a};freakdev.canvas.scene.Object.prototype.render=function(){if(!this._isRendering){this._isRendering=true;this.setNeedToRender(false);this._isRendering=false}};freakdev.canvas.scene.Object.prototype.isRendering=function(){return this._isRendering};freakdev.canvas.scene.Object.prototype.isDomEventHandled=
function(a){return this._eventListeners[a]?true:false};freakdev.canvas.scene.Object.prototype.handleDomEvent=function(a){if(!a.type)throw Error("Invalid event");if(!this.isDomEventHandled(a.type))return true;for(var b=0,c=this._eventListeners[a.type].length;b<c;b++){Fkd.call_fn_array(this._eventListeners[a.type][b],[a]);if(false===a.canPropagate())break}return a.canPropagate()};freakdev.canvas.scene.Object.prototype.removeEventListeners=function(a,b){if(this.isDomEventHandled(a))if(b){this._eventListeners[a].splice(indexof(b,
this._eventListeners[a]),1);0==this._eventListeners[a].length&&delete this._eventListeners[a]}else delete this._eventListeners[a]};freakdev.canvas.scene.Object.prototype.addEventListener=function(a,b){freakdev.event.EventManager.getInstance();this.isDomEventHandled(a)||(this._eventListeners[a]=[]);this._eventListeners[a].push(b)};freakdev.canvas.scene.Object.prototype._shouldHandleMouseEvent=function(a){var b=a.canvas.getContext();b.beginPath();b.moveTo(this.getX(),this.getY());b.lineTo(this.getX()+
this.getWidth(),this.getY());b.lineTo(this.getX()+this.getWidth(),this.getY()+this.getHeight());b.lineTo(this.getX(),this.getY()+this.getHeight());b.lineTo(this.getX(),this.getY());b.closePath();return b.isPointInPath(a.x,a.y)};freakdev.canvas.scene.Object.prototype.getWidth=function(){return this.getImgTag().width};freakdev.canvas.scene.Object.prototype.getHeight=function(){return this.getImgTag().height};freakdev.canvas.scene.Object.prototype.getX=function(){return this.x};freakdev.canvas.scene.Object.prototype.getY=
function(){return this.y};freakdev.canvas.scene.Object.prototype.getImgTag=function(){return this._imgTag};freakdev.canvas.scene.Object.prototype.getOpacity=function(){return this.opacity};freakdev.canvas.scene.Object.prototype.getRotation=function(){return this.rotation};freakdev.canvas.scene.Object.prototype.getScale=function(){return{x:this.scaleX,y:this.scaleY}};freakdev.canvas.scene.Object.prototype.getScaleX=function(){return this.scaleX};freakdev.canvas.scene.Object.prototype.getScaleY=function(){return this.scaleY};
freakdev.canvas.scene.Object.prototype.isActive=function(){return this.activeStatus};freakdev.canvas.scene.Object.prototype.hasFocus=function(){return this.focusStatus};freakdev.canvas.scene.Object.prototype.isVisible=function(){return this.visibilityStatus};freakdev.canvas.scene.Object.prototype.setOpacity=function(a){this.opacity=a};freakdev.canvas.scene.Object.prototype.setRotation=function(a){this.rotation=a};freakdev.canvas.scene.Object.prototype.setScaleX=function(a){this.scaleX=parseFloat(a);
a=this.getWidth();this.setWidth(this._naturalWidth*this.getScaleX());this.setX(this.getX()-(this.getWidth()-a)/2)};freakdev.canvas.scene.Object.prototype.setScaleY=function(a){this.scaleY=parseFloat(a);a=this.getHeight();this.setHeight(this._naturalHeight*this.getScaleY());this.setY(this.getY()-(this.getHeight()-a)/2)};freakdev.canvas.scene.Object.prototype.setScale=function(a){this.setScaleX(parseFloat(a));this.setScaleY(parseFloat(a))};freakdev.canvas.scene.Object.prototype.setImgTag=function(a){this._imgTag=
a;this._naturalWidth=this._imgTag.width;this._naturalHeight=this._imgTag.height};freakdev.canvas.scene.Object.prototype.setWidth=function(a){this.getImgTag().width=a};freakdev.canvas.scene.Object.prototype.setHeight=function(a){this.getImgTag().height=a};freakdev.canvas.scene.Object.prototype.setX=function(a){this.x=a};freakdev.canvas.scene.Object.prototype.setY=function(a){this.y=a};freakdev.canvas.scene.Object.prototype.setActive=function(a){if(undefined==a)a=true;this.activeStatus=a};freakdev.canvas.scene.Object.prototype.focus=
function(a){if(undefined==a)a=true;this.focusStatus=a};freakdev.canvas.scene.Object.prototype.setVisible=function(a){if(undefined==a)a=true;this.visibilityStatus=a};Fkd.createNamespace("freakdev.canvas.scene");freakdev.canvas.scene.DisplayGroup=Fkd.extend(freakdev.canvas.scene.Object);freakdev.canvas.scene.DisplayGroup.prototype.init=function(a,b,c,d){this._atlas=[];this.targetCanvas=null;freakdev.canvas.scene.DisplayGroup.superClass.init.call(this,a,b,c,d)};freakdev.canvas.scene.DisplayGroup.prototype.handleDomEvent=
function(a){for(var b=this._atlas.length-1;b>=0;b--){var c=this._atlas[b];if(false==c.handleDomEvent.call(c,a))break}return a.canPropagate()?freakdev.canvas.scene.DisplayGroup.superClass.handleDomEvent.call(this,a):false};freakdev.canvas.scene.DisplayGroup.prototype._drawToTarget=function(){for(var a=0,b=this._atlas.length;a<b;a++)this._atlas[a].renderTo(this.targetCanvas)};freakdev.canvas.scene.DisplayGroup.prototype._renderThreadCallback=function(){if(freakdev.thread.Broker.getInstance().isFinished(this.getId())){this._isRendering=
false;this.setNeedToRender(false);this.renderTo(this.targetCanvas)}};freakdev.canvas.scene.DisplayGroup.prototype.render=function(){if(!this._isRendering){var a=freakdev.thread.Broker.getInstance();freakdev.utils.Uuid();for(var b=0,c=this._atlas.length;b<c;b++){var d=this._atlas[b];a.startThread(Fkd.createDelegate(d.render,d),[],Fkd.createDelegate(this._renderThreadCallback,this),this.getId())}}};freakdev.canvas.scene.DisplayGroup.prototype._prepareTarget=function(a){if(this.opacity<1||0!=this.rotation||
1!=this.getScaleX()||1!=this.getScaleY()){a.updateContext("globalAlpha",this.opacity);a.translateToObjectCenter(this);tmpX=this.getX();tmpY=this.getY();this.setX(-parseInt(this.getWidth()/2));this.setY(-parseInt(this.getHeight()/2));for(var b=0,c=this._atlas.length;b<c;b++){var d=this._atlas[b];d.setX(d.getX()+this.getX());d.setY(d.getY()+this.getY())}a.rotate(this.rotation);a.scale(this.getScaleX(),this.getScaleY())}};freakdev.canvas.scene.DisplayGroup.prototype._restoreTarget=function(a){if(this.opacity<
1||0!=this.rotation||1!=this.getScaleX()||1!=this.getScaleY()){a.restore(4);this.setX(tmpX);this.setY(tmpY);a=0;for(var b=this._atlas.length;a<b;a++){var c=this._atlas[a];c.setX(c.getX()+this.getX());c.setY(c.getY()+this.getY())}}};freakdev.canvas.scene.DisplayGroup.prototype.renderTo=function(a){if(undefined!=a)this.targetCanvas=a;freakdev.canvas.scene.DisplayGroup.superClass.renderTo.call(this,this.targetCanvas)};freakdev.canvas.scene.DisplayGroup.prototype.push=function(a){a.setContainer(this);
this._atlas.push(a)};freakdev.canvas.scene.DisplayGroup.prototype.pop=function(){this._atlas.pop().setContainer(null)};freakdev.canvas.scene.DisplayGroup.prototype.unshift=function(a){a.setContainer(this);this._atlas.unshift(a)};freakdev.canvas.scene.DisplayGroup.prototype.shift=function(){this._atlas.shift().setContainer(null)};freakdev.canvas.scene.DisplayGroup.prototype.insertAt=function(a,b){b.setContainer(this);this._atlas.splice(a,0,b)};freakdev.canvas.scene.DisplayGroup.prototype.removeAt=
function(a){this._atlas.splice(a,1)[0].setContainer(null)};Fkd.createNamespace("freakdev.canvas.scene");freakdev.canvas.scene.Scene=Fkd.extend(freakdev.canvas.scene.DisplayGroup);freakdev.canvas.scene.Scene.prototype.init=function(a){freakdev.canvas.scene.Scene.superClass.init.call(this,0,0,a.width,a.height);this.targetCanvas=a};freakdev.canvas.scene.Scene.prototype.renderTo=function(a){if(undefined!=a)this.targetCanvas=a;ctx=this.targetCanvas.getContext();ctx.clearRect(0,0,this.targetCanvas.getCanvas().width,
this.targetCanvas.getCanvas().height);a=0;for(var b=this._atlas.length;a<b;a++)this._atlas[a].renderTo(this.targetCanvas)};freakdev.canvas.scene.Scene.prototype.setVisible=function(){throw Error("Can't change visibility status of the scene");};freakdev.canvas.scene.Scene.prototype.resize=function(a,b){this.setWidth(a);this.setHeight(b)};Fkd.createNamespace("freakdev.canvas.scene");freakdev.canvas.scene.Image=Fkd.extend(freakdev.canvas.scene.Object);freakdev.canvas.scene.Image.prototype.init=function(a,
b,c){b=undefined==b?0:b;c=undefined==c?0:c;if(a)if(a=freakdev.utils.Dom.get(a)){freakdev.canvas.scene.Image.superClass.init.call(this,b,c);this.setImgTag(a);return}throw Error("invalid tag");};Fkd.createNamespace("freakdev.canvas.scene");freakdev.canvas.scene.Shape=Fkd.extend(freakdev.canvas.scene.Object);freakdev.canvas.scene.Shape.prototype.init=function(){this._isMask=false;freakdev.canvas.scene.Shape.superClass.init.apply(this,arguments)};freakdev.canvas.scene.Shape.prototype.renderTo=function(a){if(undefined!=
a)this.targetCanvas=a;a=this.targetCanvas.getContext("2d");if(this.isMask()){a.beginPath();this.draw();a.closePath();a.save();a.clip()}else freakdev.canvas.scene.Shape.superClass.renderTo.call(this,this.targetCanvas)};freakdev.canvas.scene.Shape.prototype.draw=function(){throw Error("should be implemented by the children class");};freakdev.canvas.scene.Shape.prototype.isMask=function(){return this._isMask};freakdev.canvas.scene.Shape.prototype.setAsMask=function(){this._isMask=true;freakdev.event.EventManager.getInstance();
this._container.attachEvent("afterRenderTo",Fkd.createDelegate(function(){this.targetCanvas.restore()},this))};Fkd.createNamespace("freakdev.canvas.scene");freakdev.canvas.scene.Path=Fkd.extend(freakdev.canvas.scene.Shape);freakdev.canvas.scene.Path.prototype.init=function(a){freakdev.canvas.scene.Path.superClass.init.call(this);this._points=undefined==a?[]:a;this._canvas=document.createElement("canvas");this._renderIndex=0;this.targetCanvas=null};freakdev.canvas.scene.Path.setTarget=function(a){this.targetCanvas=
a};freakdev.canvas.scene.Path.prototype.beginPath=function(){this.targetCanvas.getContext("2d").beginPath()};freakdev.canvas.scene.Path.prototype.closePath=function(){this.targetCanvas.getContext("2d").closePath()};freakdev.canvas.scene.Path.prototype.draw=function(a,b){if(undefined==b)b=this.targetCanvas.getContext("2d");if(undefined==a)a=this._points;if(a.length){b.moveTo(a[0].x,a[0].y);for(var c=1,d=a.length;c<d;c++)b.lineTo(a[c].x,a[c].y)}};freakdev.canvas.scene.Path.prototype.render=function(){if(!this._isRendering){this._isRendering=
true;this.setNeedToRender(false);var a=this._canvas.getContext("2d"),b=this._points.slice(this._renderIndex);this._renderIndex=this._points.length>2?this._points.length-1:0;if(b.length){this.draw(b,a);a.stroke();var c=new Image;c.onload=Fkd.createDelegate(function(){this.setImgTag(c);this._isRendering=false},this);c.src=this._canvas.toDataURL()}delete a;delete b}};freakdev.canvas.scene.Path.prototype.push=function(a){this.setNeedToRender();this._points.push(a)};freakdev.canvas.scene.Path.prototype.setContainer=
function(a){freakdev.canvas.scene.Path.superClass.setContainer.call(this,a);if(this._container){this.setWidth(this._container.getWidth());this.setHeight(this._container.getHeight());this.setX(this._container.getX());this.setY(this._container.getY())}};freakdev.canvas.scene.Path.prototype.setWidth=function(a){this._canvas.width=a};freakdev.canvas.scene.Path.prototype.setHeight=function(a){this._canvas.height=a};Fkd.createNamespace("freakdev.thread");freakdev.thread.Broker=function(){this.init.apply(this,
arguments)};freakdev.thread.Broker.instance=null;freakdev.thread.Broker.getInstance=function(){if(!freakdev.thread.Broker.instance)freakdev.thread.Broker.instance=new freakdev.thread.Broker;return freakdev.thread.Broker.instance};freakdev.thread.Broker.prototype.init=function(){this.nbStarted=0;this.threads=[];this.threadStack=[]};freakdev.thread.Broker.prototype.startThread=function(a,b,c,d){if(undefined==d)d=(new Date).getTime();d=d.toString();if(undefined==b)b=[];if(undefined==c)c=function(){};
a=new freakdev.thread.Thread(a,b,c);if(undefined==this.threads[d]||null==this.threads[d]){this.threads[d]=[a];this.threadStack.push(d)}else this.threads[d].push(a);var e=document.createElement("script");e.src="data:text/javascript,";e.onload=Fkd.createDelegate(function(){document.body.removeChild(e);this.processStack()},this);document.getElementsByTagName("body").item(0).appendChild(e)};freakdev.thread.Broker.prototype.processStack=function(){this.nbStarted++;var a=this.threadStack[0];if(this.threads[a]){var b=
this.threads[a].shift(),c=b.run();this.nbStarted--;if(0==this.threads[a].length){delete this.threads[a];this.threadStack.splice(0,1)}b.callback(c)}};freakdev.thread.Broker.prototype.isFinished=function(a){return this.threadStack.indexOf(a.toString())==-1?true:false};Fkd.createNamespace("freakdev.thread");freakdev.thread.Thread=function(){this.init.apply(this,arguments)};freakdev.thread.Thread.prototype.init=function(a,b,c){this.fn=a;this.params=b;this.callback=c};freakdev.thread.Thread.prototype.run=
function(){return this.fn(this.params)}})();
